# add stages here 
# stages:
#   stage_name:
#     cmd: python src/stage_01______.py
#     deps:
#     - src/stage_01______.py
#     outs:
#     - output_data_of_file_path

# add stages here 
stages:
  get_data:
    cmd: python src/stage_01_get_data.py --config=configs/config.yaml
    deps:
    - src/stage_01_get_data.py
    - src/utils/common.py
    - configs/config.yaml
    outs:
    - data/breakfast_burrito
    - data/gyoza
    - data/ravioli
    - data/gnocchi
    - data/spaghetti_carbonara
    - data/creme_brulee
    - data/cheese_plate
    - data/chocolate_cake
    - data/french_onion_soup
    - data/clam_chowder
    - data/hamburger
    - data/prime_rib
    - data/escargots
    - data/waffles
    - data/grilled_cheese_sandwich
    - data/omelette
    - data/hot_and_sour_soup
    - data/sashimi
    - data/ramen
    - data/pork_chop
    - data/eggs_benedict
    - data/pho
    - data/garlic_bread
    - data/panna_cotta
    - data/donuts
    - data/lasagna
    - data/mussels
    - data/steak
    - data/spring_rolls
    - data/hummus
    - data/fried_calamari
    - data/ceviche
    - data/dumplings
    - data/ice_cream
    - data/french_fries
    - data/tiramisu
    - data/seaweed_salad
    - data/samosa
    - data/beef_tartare
    - data/miso_soup
    - data/hot_dog
    - data/baklava
    - data/pulled_pork_sandwich
    - data/french_toast
    - data/baby_back_ribs
    - data/lobster_bisque
    - data/croque_madame
    - data/nachos
    - data/oysters
    - data/filet_mignon
    - data/pad_thai
    - data/club_sandwich
    - data/shrimp_and_grits
    - data/takoyaki
    - data/huevos_rancheros
    - data/paella
    - data/greek_salad
    - data/churros
    - data/chicken_curry
    - data/frozen_yogurt
    - data/chicken_wings
    - data/tuna_tartare
    - data/chicken_quesadilla
    - data/fried_rice
    - data/bread_pudding
    - data/strawberry_shortcake
    - data/red_velvet_cake
    - data/cup_cakes
    - data/cannoli
    - data/apple_pie
    - data/caesar_salad
    - data/peking_duck
    - data/guacamole
    - data/cheesecake
    - data/bruschetta
    - data/edamame
    - data/spaghetti_bolognese
    - data/lobster_roll_sandwich
    - data/beignets
    - data/risotto
    - data/bibimbap
    - data/poutine
    - data/beef_carpaccio
    - data/grilled_salmon
    - data/falafel
    - data/chocolate_mousse
    - data/sushi
    - data/macarons
    - data/tacos
    - data/foie_gras
    - data/scallops
    - data/pizza
    - data/carrot_cake
    - data/crab_cakes
    - data/macaroni_and_cheese
    - data/onion_rings
    - data/fish_and_chips
    - data/pancakes
    - data/deviled_eggs
    - data/caprese_salad
    - data/beet_salad


  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_02_prepare_base_model.py
    - src/utils/common.py
    - src/utils/model.py
    - configs/config.yaml
    params:
    - IMAGE_SIZE
    - LEARNING_RATE
    outs:
    - artifacts/base_model/base_model.h5
    - artifacts/base_model/updated_base_model.h5


  prepare_callback:
    cmd: python src/stage_03_prepare_callback.py --config=configs/config.yaml
    deps:
    - src/stage_03_prepare_callback.py
    - src/utils/common.py
    - src/utils/callbacks.py
    - configs/config.yaml
    - params.yaml
    outs:
    - artifacts/callbacks/checkpoint_cb.cb
    - artifacts/callbacks/tensorboard_cb.cb


  train:
    cmd: python src/stage_04_train.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_04_train.py
    - src/utils/common.py
    - src/utils/model.py
    - src/utils/callbacks.py
    - src/utils/data_management.py
    - configs/config.yaml
    - artifacts/callbacks/checkpoint_cb.cb
    - artifacts/callbacks/tensorboard_cb.cb
    - artifacts/base_model/updated_base_model.h5
    - data/breakfast_burrito
    - data/gyoza
    - data/ravioli
    - data/gnocchi
    - data/spaghetti_carbonara
    - data/creme_brulee
    - data/cheese_plate
    - data/chocolate_cake
    - data/french_onion_soup
    - data/clam_chowder
    - data/hamburger
    - data/prime_rib
    - data/escargots
    - data/waffles
    - data/grilled_cheese_sandwich
    - data/omelette
    - data/hot_and_sour_soup
    - data/sashimi
    - data/ramen
    - data/pork_chop
    - data/eggs_benedict
    - data/pho
    - data/garlic_bread
    - data/panna_cotta
    - data/donuts
    - data/lasagna
    - data/mussels
    - data/steak
    - data/spring_rolls
    - data/hummus
    - data/fried_calamari
    - data/ceviche
    - data/dumplings
    - data/ice_cream
    - data/french_fries
    - data/tiramisu
    - data/seaweed_salad
    - data/samosa
    - data/beef_tartare
    - data/miso_soup
    - data/hot_dog
    - data/baklava
    - data/pulled_pork_sandwich
    - data/french_toast
    - data/baby_back_ribs
    - data/lobster_bisque
    - data/croque_madame
    - data/nachos
    - data/oysters
    - data/filet_mignon
    - data/pad_thai
    - data/club_sandwich
    - data/shrimp_and_grits
    - data/takoyaki
    - data/huevos_rancheros
    - data/paella
    - data/greek_salad
    - data/churros
    - data/chicken_curry
    - data/frozen_yogurt
    - data/chicken_wings
    - data/tuna_tartare
    - data/chicken_quesadilla
    - data/fried_rice
    - data/bread_pudding
    - data/strawberry_shortcake
    - data/red_velvet_cake
    - data/cup_cakes
    - data/cannoli
    - data/apple_pie
    - data/caesar_salad
    - data/peking_duck
    - data/guacamole
    - data/cheesecake
    - data/bruschetta
    - data/edamame
    - data/spaghetti_bolognese
    - data/lobster_roll_sandwich
    - data/beignets
    - data/risotto
    - data/bibimbap
    - data/poutine
    - data/beef_carpaccio
    - data/grilled_salmon
    - data/falafel
    - data/chocolate_mousse
    - data/sushi
    - data/macarons
    - data/tacos
    - data/foie_gras
    - data/scallops
    - data/pizza
    - data/carrot_cake
    - data/crab_cakes
    - data/macaroni_and_cheese
    - data/onion_rings
    - data/fish_and_chips
    - data/pancakes
    - data/deviled_eggs
    - data/caprese_salad
    - data/beet_salad
    params:
    - IMAGE_SIZE
    - BATCH_SIZE
    - AUGMENTATION
    - EPOCHS
    outs:
    - artifacts/model
    - artifacts/tensorboard_log_dir
    - artifacts/checkpoints