# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: data

# you can download the dataset from the link: https://drive.google.com/drive/folders/1Z2c3e_rGBGV8wHValqT6Va4uomP246Lv?usp=sharing
# if you download the dataset, you need to store it outside of the project directory and then call it through the method below.
source_data_dirs:
  - ../101_food_classes_data/breakfast_burrito
  - ../101_food_classes_data/gyoza
  - ../101_food_classes_data/ravioli
  - ../101_food_classes_data/gnocchi
  - ../101_food_classes_data/spaghetti_carbonara
  - ../101_food_classes_data/creme_brulee
  - ../101_food_classes_data/cheese_plate
  - ../101_food_classes_data/chocolate_cake
  - ../101_food_classes_data/french_onion_soup
  - ../101_food_classes_data/clam_chowder
  - ../101_food_classes_data/hamburger
  - ../101_food_classes_data/prime_rib
  - ../101_food_classes_data/escargots
  - ../101_food_classes_data/waffles
  - ../101_food_classes_data/grilled_cheese_sandwich
  - ../101_food_classes_data/omelette
  - ../101_food_classes_data/hot_and_sour_soup
  - ../101_food_classes_data/sashimi
  - ../101_food_classes_data/ramen
  - ../101_food_classes_data/pork_chop
  - ../101_food_classes_data/eggs_benedict
  - ../101_food_classes_data/pho
  - ../101_food_classes_data/garlic_bread
  - ../101_food_classes_data/panna_cotta
  - ../101_food_classes_data/donuts
  - ../101_food_classes_data/lasagna
  - ../101_food_classes_data/mussels
  - ../101_food_classes_data/steak
  - ../101_food_classes_data/spring_rolls
  - ../101_food_classes_data/hummus
  - ../101_food_classes_data/fried_calamari
  - ../101_food_classes_data/ceviche
  - ../101_food_classes_data/dumplings
  - ../101_food_classes_data/ice_cream
  - ../101_food_classes_data/french_fries
  - ../101_food_classes_data/tiramisu
  - ../101_food_classes_data/seaweed_salad
  - ../101_food_classes_data/samosa
  - ../101_food_classes_data/beef_tartare
  - ../101_food_classes_data/miso_soup
  - ../101_food_classes_data/hot_dog
  - ../101_food_classes_data/baklava
  - ../101_food_classes_data/pulled_pork_sandwich
  - ../101_food_classes_data/french_toast
  - ../101_food_classes_data/baby_back_ribs
  - ../101_food_classes_data/lobster_bisque
  - ../101_food_classes_data/croque_madame
  - ../101_food_classes_data/nachos
  - ../101_food_classes_data/oysters
  - ../101_food_classes_data/filet_mignon
  - ../101_food_classes_data/pad_thai
  - ../101_food_classes_data/club_sandwich
  - ../101_food_classes_data/shrimp_and_grits
  - ../101_food_classes_data/takoyaki
  - ../101_food_classes_data/huevos_rancheros
  - ../101_food_classes_data/paella
  - ../101_food_classes_data/greek_salad
  - ../101_food_classes_data/churros
  - ../101_food_classes_data/chicken_curry
  - ../101_food_classes_data/frozen_yogurt
  - ../101_food_classes_data/chicken_wings
  - ../101_food_classes_data/tuna_tartare
  - ../101_food_classes_data/chicken_quesadilla
  - ../101_food_classes_data/fried_rice
  - ../101_food_classes_data/bread_pudding
  - ../101_food_classes_data/strawberry_shortcake
  - ../101_food_classes_data/red_velvet_cake
  - ../101_food_classes_data/cup_cakes
  - ../101_food_classes_data/cannoli
  - ../101_food_classes_data/apple_pie
  - ../101_food_classes_data/caesar_salad
  - ../101_food_classes_data/peking_duck
  - ../101_food_classes_data/guacamole
  - ../101_food_classes_data/cheesecake
  - ../101_food_classes_data/bruschetta
  - ../101_food_classes_data/edamame
  - ../101_food_classes_data/spaghetti_bolognese
  - ../101_food_classes_data/lobster_roll_sandwich
  - ../101_food_classes_data/beignets
  - ../101_food_classes_data/risotto
  - ../101_food_classes_data/bibimbap
  - ../101_food_classes_data/poutine
  - ../101_food_classes_data/beef_carpaccio
  - ../101_food_classes_data/grilled_salmon
  - ../101_food_classes_data/falafel
  - ../101_food_classes_data/chocolate_mousse
  - ../101_food_classes_data/sushi
  - ../101_food_classes_data/macarons
  - ../101_food_classes_data/tacos
  - ../101_food_classes_data/foie_gras
  - ../101_food_classes_data/scallops
  - ../101_food_classes_data/pizza
  - ../101_food_classes_data/carrot_cake
  - ../101_food_classes_data/crab_cakes
  - ../101_food_classes_data/macaroni_and_cheese
  - ../101_food_classes_data/onion_rings
  - ../101_food_classes_data/fish_and_chips
  - ../101_food_classes_data/pancakes
  - ../101_food_classes_data/deviled_eggs
  - ../101_food_classes_data/caprese_salad
  - ../101_food_classes_data/beet_salad

local_data_dirs:
  - data/breakfast_burrito
  - data/gyoza
  - data/ravioli
  - data/gnocchi
  - data/spaghetti_carbonara
  - data/creme_brulee
  - data/cheese_plate
  - data/chocolate_cake
  - data/french_onion_soup
  - data/clam_chowder
  - data/hamburger
  - data/prime_rib
  - data/escargots
  - data/waffles
  - data/grilled_cheese_sandwich
  - data/omelette
  - data/hot_and_sour_soup
  - data/sashimi
  - data/ramen
  - data/pork_chop
  - data/eggs_benedict
  - data/pho
  - data/garlic_bread
  - data/panna_cotta
  - data/donuts
  - data/lasagna
  - data/mussels
  - data/steak
  - data/spring_rolls
  - data/hummus
  - data/fried_calamari
  - data/ceviche
  - data/dumplings
  - data/ice_cream
  - data/french_fries
  - data/tiramisu
  - data/seaweed_salad
  - data/samosa
  - data/beef_tartare
  - data/miso_soup
  - data/hot_dog
  - data/baklava
  - data/pulled_pork_sandwich
  - data/french_toast
  - data/baby_back_ribs
  - data/lobster_bisque
  - data/croque_madame
  - data/nachos
  - data/oysters
  - data/filet_mignon
  - data/pad_thai
  - data/club_sandwich
  - data/shrimp_and_grits
  - data/takoyaki
  - data/huevos_rancheros
  - data/paella
  - data/greek_salad
  - data/churros
  - data/chicken_curry
  - data/frozen_yogurt
  - data/chicken_wings
  - data/tuna_tartare
  - data/chicken_quesadilla
  - data/fried_rice
  - data/bread_pudding
  - data/strawberry_shortcake
  - data/red_velvet_cake
  - data/cup_cakes
  - data/cannoli
  - data/apple_pie
  - data/caesar_salad
  - data/peking_duck
  - data/guacamole
  - data/cheesecake
  - data/bruschetta
  - data/edamame
  - data/spaghetti_bolognese
  - data/lobster_roll_sandwich
  - data/beignets
  - data/risotto
  - data/bibimbap
  - data/poutine
  - data/beef_carpaccio
  - data/grilled_salmon
  - data/falafel
  - data/chocolate_mousse
  - data/sushi
  - data/macarons
  - data/tacos
  - data/foie_gras
  - data/scallops
  - data/pizza
  - data/carrot_cake
  - data/crab_cakes
  - data/macaroni_and_cheese
  - data/onion_rings
  - data/fish_and_chips
  - data/pancakes
  - data/deviled_eggs
  - data/caprese_salad
  - data/beet_salad